<?php

/**
 * BaseJobCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property integer $job_id
 * @property Company $Company
 * @property Job $Job
 * 
 * @method integer    getCompanyId()  Returns the current record's "company_id" value
 * @method integer    getJobId()      Returns the current record's "job_id" value
 * @method Company    getCompany()    Returns the current record's "Company" value
 * @method Job        getJob()        Returns the current record's "Job" value
 * @method JobCompany setCompanyId()  Sets the current record's "company_id" value
 * @method JobCompany setJobId()      Sets the current record's "job_id" value
 * @method JobCompany setCompany()    Sets the current record's "Company" value
 * @method JobCompany setJob()        Sets the current record's "Job" value
 * 
 * @package    Physalix_Backend
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job_company');
        $this->hasColumn('company_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('job_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Job', array(
             'local' => 'job_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}