<?php

/**
 * BaseJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $date_presentation
 * @property integer $position_id
 * @property float $tjm
 * @property integer $client_id
 * @property boolean $statut
 * @property string $commentaire
 * @property Company $Company
 * @property Position $Position
 * @property Doctrine_Collection $JobCompany
 * @property Doctrine_Collection $JobContact
 * 
 * @method timestamp           getDatePresentation()  Returns the current record's "date_presentation" value
 * @method integer             getPositionId()        Returns the current record's "position_id" value
 * @method float               getTjm()               Returns the current record's "tjm" value
 * @method integer             getClientId()          Returns the current record's "client_id" value
 * @method boolean             getStatut()            Returns the current record's "statut" value
 * @method string              getCommentaire()       Returns the current record's "commentaire" value
 * @method Company             getCompany()           Returns the current record's "Company" value
 * @method Position            getPosition()          Returns the current record's "Position" value
 * @method Doctrine_Collection getJobCompany()        Returns the current record's "JobCompany" collection
 * @method Doctrine_Collection getJobContact()        Returns the current record's "JobContact" collection
 * @method Job                 setDatePresentation()  Sets the current record's "date_presentation" value
 * @method Job                 setPositionId()        Sets the current record's "position_id" value
 * @method Job                 setTjm()               Sets the current record's "tjm" value
 * @method Job                 setClientId()          Sets the current record's "client_id" value
 * @method Job                 setStatut()            Sets the current record's "statut" value
 * @method Job                 setCommentaire()       Sets the current record's "commentaire" value
 * @method Job                 setCompany()           Sets the current record's "Company" value
 * @method Job                 setPosition()          Sets the current record's "Position" value
 * @method Job                 setJobCompany()        Sets the current record's "JobCompany" collection
 * @method Job                 setJobContact()        Sets the current record's "JobContact" collection
 * 
 * @package    Physalix_Backend
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJob extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job');
        $this->hasColumn('date_presentation', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('position_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('tjm', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('client_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('statut', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('commentaire', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('Position', array(
             'local' => 'position_id',
             'foreign' => 'id'));

        $this->hasMany('JobCompany', array(
             'local' => 'id',
             'foreign' => 'job_id'));

        $this->hasMany('JobContact', array(
             'local' => 'id',
             'foreign' => 'job_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}