<?php

/**
 * BaseJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $client_id
 * @property timestamp $date_presentation
 * @property integer $position_id
 * @property float $tjm
 * @property integer $fournisseur_id
 * @property integer $contact_id
 * @property boolean $statut
 * @property string $commentaire
 * @property Company $Fournisseur
 * @property Company $Client
 * @property Position $Position
 * @property Contact $Contact
 * 
 * @method integer   getClientId()          Returns the current record's "client_id" value
 * @method timestamp getDatePresentation()  Returns the current record's "date_presentation" value
 * @method integer   getPositionId()        Returns the current record's "position_id" value
 * @method float     getTjm()               Returns the current record's "tjm" value
 * @method integer   getFournisseurId()     Returns the current record's "fournisseur_id" value
 * @method integer   getContactId()         Returns the current record's "contact_id" value
 * @method boolean   getStatut()            Returns the current record's "statut" value
 * @method string    getCommentaire()       Returns the current record's "commentaire" value
 * @method Company   getFournisseur()       Returns the current record's "Fournisseur" value
 * @method Company   getClient()            Returns the current record's "Client" value
 * @method Position  getPosition()          Returns the current record's "Position" value
 * @method Contact   getContact()           Returns the current record's "Contact" value
 * @method Job       setClientId()          Sets the current record's "client_id" value
 * @method Job       setDatePresentation()  Sets the current record's "date_presentation" value
 * @method Job       setPositionId()        Sets the current record's "position_id" value
 * @method Job       setTjm()               Sets the current record's "tjm" value
 * @method Job       setFournisseurId()     Sets the current record's "fournisseur_id" value
 * @method Job       setContactId()         Sets the current record's "contact_id" value
 * @method Job       setStatut()            Sets the current record's "statut" value
 * @method Job       setCommentaire()       Sets the current record's "commentaire" value
 * @method Job       setFournisseur()       Sets the current record's "Fournisseur" value
 * @method Job       setClient()            Sets the current record's "Client" value
 * @method Job       setPosition()          Sets the current record's "Position" value
 * @method Job       setContact()           Sets the current record's "Contact" value
 * 
 * @package    Physalix_Backend
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJob extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job');
        $this->hasColumn('client_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('date_presentation', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('position_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('tjm', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('fournisseur_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('contact_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('statut', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('commentaire', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company as Fournisseur', array(
             'local' => 'fournisseur_id',
             'foreign' => 'id'));

        $this->hasOne('Company as Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('Position', array(
             'local' => 'position_id',
             'foreign' => 'id'));

        $this->hasOne('Contact', array(
             'local' => 'contact_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}