<?php

/**
 * BaseJobContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $contact_id
 * @property integer $job_id
 * @property Contact $Contact
 * @property Job $Job
 * 
 * @method integer    getContactId()  Returns the current record's "contact_id" value
 * @method integer    getJobId()      Returns the current record's "job_id" value
 * @method Contact    getContact()    Returns the current record's "Contact" value
 * @method Job        getJob()        Returns the current record's "Job" value
 * @method JobContact setContactId()  Sets the current record's "contact_id" value
 * @method JobContact setJobId()      Sets the current record's "job_id" value
 * @method JobContact setContact()    Sets the current record's "Contact" value
 * @method JobContact setJob()        Sets the current record's "Job" value
 * 
 * @package    Physalix_Backend
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job_contact');
        $this->hasColumn('contact_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('job_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contact', array(
             'local' => 'contact_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Job', array(
             'local' => 'job_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}