<?php

/**
 * ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contact');
    }

    /**
     * Returns a list of jobs by contact id.
     *
     * @return object JobTable
     */
	public function getContactsByCompanyId($companyId) 
	{
		$q = $this->createQuery('j')
			->where('j.company_id = ?', $companyId)
			->orderBy('j.nom DESC');

		return $q->execute();
	}

}