<?php

/**
 * JobCompanyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobCompanyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobCompanyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobCompany');
    }
}