<?php

/**
 * JobContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobContact');
    }
}