<?php

/**
 * JobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Job');
    }

    /**
     * Returns a list of jobs by contact id.
     *
     * @return object JobTable
     */
	public function getJobsByContactId($contactId) 
	{
		$q = $this->createQuery('j')
			->where('j.contact_id = ?', $contactId)
			->orderBy('j.created_at DESC');
			
		return $q->execute();
	}
}