<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/04 15:57:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=physalix_backend',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
